# Generated by Django 4.2.5 on 2023-09-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_trainer_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='profile',
            field=models.ImageField(null=True, upload_to='trainers_profile/'),
        ),
    ]
