# Generated by Django 4.2.5 on 2023-09-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_alter_trainer_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
